


from mysql.connector import Error
from persistance.db import get_connection